personal/code/ruby/rails/friends/config/routes.rb
Rails.application.routes.draw do
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

personal/code/ruby/rails/friends/app/models/friend.rb
class Friend < ApplicationRecord
end

personal/code/ruby/rails/friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

personal/code/ruby/rails/friends/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone)
    end
end

personal/code/ruby/rails/friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

personal/code/ruby/rails/friends/app/helpers/friends_helper.rb
module FriendsHelper
end

personal/code/ruby/rails/friends/app/helpers/home_helper.rb
module HomeHelper
end

personal/code/ruby/rails/friends/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

personal/code/ruby/rails/friends/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

</div>

personal/code/ruby/rails/friends/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

personal/code/ruby/rails/friends/app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend %>
    </p>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path %>

personal/code/ruby/rails/friends/app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

personal/code/ruby/rails/friends/app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

personal/code/ruby/rails/friends/app/views/home/_header.html.erb
<div class="container">
  <nav>
    <ul>
      <li data-tooltip="Go to home" data-placement="right"><strong><%= link_to 'Friend List', root_path %></strong></li>

    </ul>
    <ul>
      <li><%= link_to 'About us', home_about_path %></li>
      <li><%= link_to 'Friend', friends_path %></li>
      <li><%= link_to 'New Friend', new_friend_path %></li>
    </ul>
  </nav>
</div>

personal/code/ruby/rails/friends/app/views/home/about.html.erb
<h1>About</h1>
This is an about page.

personal/code/ruby/rails/friends/app/views/home/index.html.erb
<h1>Why are you here?</h1>
<h2>Why are you here?</h2>
<h3>Why are you here?</h3>
<h4>Why are you here?</h4>
<h5>Why are you here?</h5>
<h6>Why are you here?</h6>

personal/code/ruby/rails/friends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Pico.css -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@2.0.6/css/pico.min.css"
    />
  </head>

  <body>
    <%= render "home/header" %>
    <div class="container">
      <br>
      <%= yield %>
    </div>
  </body>
</html>